name: rada360
description: "Rada360"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: any

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.5

  flavor_config: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.4

  shared_preferences: ^2.3.2
  get_it: ^8.0.0

  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_lorem: ^2.0.0

  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  lottie: ^3.1.2
  pin_code_fields: ^8.0.1

  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.4.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Generate images, fonts, database...
  build_runner:
  flutter_gen_runner:
  hive_generator: ^2.0.0
  analyzer:

flutter_intl:
  enabled: true
  output_dir: lib/gen/localization

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SVN-Gilroy
      fonts:
        - asset: "assets/fonts/SVN-Gilroy Bold.otf"
          weight: 700
        - asset: "assets/fonts/SVN-Gilroy SemiBold.otf"
          weight: 600
        - asset: "assets/fonts/SVN-Gilroy Medium.otf"
          weight: 500
        - asset: "assets/fonts/SVN-Gilroy Regular.otf"
          weight: 400
        - asset: "assets/fonts/SVN-Gilroy Light.otf"
          weight: 300
  #      - asset: fonts/Schyler-Italic.ttf
  #         style: italic
